# -*- coding: utf-8 -*-
"""demo02-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k5ecISmfepqeJ_yHPXFmofxBciQwXA89
"""

import wave
wf = wave.open('dog.wav')
print(wf.getnchannels())

print(wf.getframerate())

print(wf.getnframes())

print(wf.getsampwidth())

wf.close()

"""The number of channels is 1, frame rate is 16000Hz and the width of the samples is 2 bytes( 16 bits). So the provided information matches the intended properties of the wave file."""